### ISSUE TITLE
using switch-window across multiple frames

### ISSUE THREAD

**Issue by denlab** [dimitri/switch-window#15]
Is it possible ? 

From the source it seems that hacking:

``` el
(defun switch-window-list (&optional from-current-window)
  "list windows for current frame, starting at top left unless
from-current-window is not nil"
  (if (or from-current-window switch-window-relative)
      (window-list nil nil)
    (window-list nil nil (frame-first-window))))
```

would do the job, am I right? 

Thx!

**Comment by akirak** [comment]
I've implemented this: https://github.com/akirak/switch-window/commit/80903293290bfa1878fbeb5a592d239b82db0e7e

To use the feature, set `switch-window-multiple-frames` to non-nil.

**Comment by tumashu** [comment]
This feature is added by @akirak
