### ISSUE TITLE
Necessary to Display Window Number When There Are Only 2 Windows?

### ISSUE THREAD

**Issue by sshaw** [dimitri/switch-window#21]
`switch-window-threshold`'s default sorta takes care of this but, if a window's frame count passes then returns to the threshold, window numbers will still be displayed on `C-x o`.

Based on this variables description this behavior makes sense, as it just *activates* it, but there should be a counter that is refreshed when a frame's windows are modified, preventing one from unnecessarily having to choose a window when the choice is obvious.

**Comment by tumashu** [comment]
```
(defun my-switch-window ()
  (interactive)
  (switch-window--then
   "Move to window: "
   #'(lambda () (other-window 1))
   nil nil 1))
```
