### ISSUE TITLE
switch-window uses buffer-local setting of cursor-type when restoring cursor type in other buffers

### ISSUE THREAD

**Issue by kcandrews** [dimitri/switch-window#24]
I use `stripe-buffer.el` in my dired buffers along with `switch-window` and found I needed to make a wrapper function around `switch-window` setting the cursor type to my preferred default cursor since I use a buffer-local cursor-type of nil in my dired buffers. Is there a cleaner way of restoring cursor type than just relying on whatever was in the previous buffer?

**Comment by sabof** [comment]
Instead of ` (original-cursor cursor-type)` it should say  `(original-cursor (default-value 'cursor-type))`

**Comment by dimitri** [comment]
Could you test the solution and propose a pull request?

**Comment by dimitri** [comment]
closed thanks to #25.
