### ISSUE TITLE
use to switch buffers in windows 

### ISSUE THREAD

**Issue by gempesaw** [dimitri/switch-window#26]
Say I have three windows open: 

    a | b | c

and I'd like to have the left most buffer in the middle window, and the middle buffer in the left most window:

    b | a | c

Does this sound like a feasible thing that I could write a switch window function to do? I'd be in window `a`, invoke `switch-window-switch-contents` or whatever, choose the middle window, and it would exchange the buffer-window contents. Or maybe even already implemented? If you think it's feasible I'll take a crack at it! :)

**Comment by dimitri** [comment]
Have a look at `buffer-move`, as found at least in el-get, maybe in ELPA and others. It's exactly what you want.

**Comment by gempesaw** [comment]
ah perfect, thanks!
