### ISSUE TITLE
Error trying to use switch-window-minibuffer-shortcut

### ISSUE THREAD

**Issue by pheaver** [dimitri/switch-window#47]
I set it like this:

    (setq switch-window-minibuffer-shortcut "z")

But most commands from `switch-window` now give this error:

    Wrong type argument: characterp, "z"

**Comment by tumashu** [comment]
it may be a doc error, try (setq switch-window-minibuffer-shortcut ?z)

**Comment by pheaver** [comment]
That seems to fix the problem. I'm getting a separate error now that's probably unrelated:

    user-error: Cannot increase the default face height more than it already is

**Comment by tumashu** [comment]
Seem to fixed, please try again

**Comment by pheaver** [comment]
Yes, it works now, thanks!
