### ISSUE TITLE
Unknown upattern `quote asciiart`

### ISSUE THREAD

**Issue by bowenchen6** [dimitri/switch-window#50]
When I enter C-x o in my emacs, something happen:
Eager macro-expansion failure: (error "Unknown upattern `(quote asciiart)'")

**Comment by tumashu** [comment]
how do you set switch-window-shortcut-appearance?

**Comment by bowenchen6** [comment]
I use the purcell/emacs.d configuration

**Comment by tumashu** [comment]
I suggest you disable purcell/emacs.d and use emacs -q  to test switc-window

**Comment by bowenchen6** [comment]
this way is good
