### ISSUE TITLE
Customize label face?

### ISSUE THREAD

**Issue by seagle0128** [dimitri/switch-window#65]
`switch-window` is stable and fast. I switched from `ace-window`.

Actually this is a new feature request to customize the label face like `ace-window`. Different color or size will make it more fancy. 

Moreover, it's better provide the customization to keep the background display, which is similar as `aw-background` of `ace-window`.

**Comment by tumashu** [comment]
different window has different color?
background mean text in window?

**Comment by seagle0128** [comment]
I mean the color, size of the labels can be customized. e.g. I can change the font color to blue or red, not only white.

Yes, background is the text in window.

Anyway, these are optional features, but please think about it. Thanks.

**Comment by tumashu** [comment]
Added

**Comment by seagle0128** [comment]
Thanks very much! It does work well.
One minor suggestion, the background shows the top of the buffer. Is it possible to show the current position of the buffer? Just like `ace-window` does.

**Comment by tumashu** [comment]
switch-window is no possible get the same effect as ace-window, I don't know whether it useful, I have update the code, you can try.

**Comment by seagle0128** [comment]
Thanks anyway.
