### ISSUE TITLE
Use popup in ascii mode

### ISSUE THREAD

**Issue by Ergus** [dimitri/switch-window#78]
Hi:

Very thanks for implementing this. I really like the package but it is a shame that the buffer's content is hidden in ascii mode; it feels unnatural. 

Could you consider to use popups or anything else that doesn't hides the whole window content, but just the region where the ascii-art letter appears in terminal?

Thanks in advance,
Ergus

**Comment by tumashu** [comment]
maybe you need ace-window :-)

**Comment by Ergus** [comment]
> maybe you need ace-window :-)

Je je, it doesn't have the ascii view plus some other useful options. That's why I moved from ace window some time ago. But this specific detail is specially annoying. (because y use only terminal emacs indeed)

**Comment by tumashu** [comment]
you can try the below config, but not beautiful :-)
```
(setq switch-window-background t)
(setq switch-window-shortcut-appearance 'asciiart)
```

**Comment by Ergus** [comment]
> you can try the below config, but not beautiful :-)
> 
> ```
> (setq switch-window-background t)
> (setq switch-window-shortcut-appearance 'asciiart)
> ```

This is perfect!! thanks!
