### ISSUE TITLE
wish: show buffer contents while displaying numbers

### ISSUE THREAD

**Issue by GregorZattler** [dimitri/switch-window#8]
switch-window is really great.  This is a feature request:  For me it would be even better if I could see the contents of the windwos after hitting C-x o.  Is it possible to overlay the windows contents with the numbers shown in order to switch to a window?

**Comment by mstorus** [comment]
@dimitri @zwass I think displaying the number on the mode line would still be a nice addition.

I prefer to use `switch-window` over `window-number` due to nice default keybindings, customizability of `switch-window-threshold`, etc.

**Comment by dimitri** [comment]
Consider sending a patch to that effect ;-)

**Comment by tumashu** [comment]
you can try ace-window https://github.com/abo-abo/ace-window
